// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/ikun2021/gex/app/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 新增币种
				Method:  http.MethodPost,
				Path:    "/add_coin",
				Handler: AddCoinHandler(serverCtx),
			},
			{
				// 新增错误码
				Method:  http.MethodPost,
				Path:    "/add_error_code",
				Handler: AddErrorCodeHandler(serverCtx),
			},
			{
				// 新增交易对
				Method:  http.MethodPost,
				Path:    "/add_symbol",
				Handler: AddSymbolHandler(serverCtx),
			},
			{
				// 币种列表
				Method:  http.MethodGet,
				Path:    "/get_coin_list",
				Handler: GetCoinListHandler(serverCtx),
			},
			{
				// 获取错误码列表
				Method:  http.MethodGet,
				Path:    "/get_error_code_list",
				Handler: GetErrorCodeListHandler(serverCtx),
			},
			{
				// 获取撮合列表
				Method:  http.MethodPost,
				Path:    "/get_match_list",
				Handler: GetMatchListHandler(serverCtx),
			},
			{
				// 获取服务配置
				Method:  http.MethodPost,
				Path:    "/get_service_config",
				Handler: GetServiceConfigHandler(serverCtx),
			},
			{
				// 获取交易对列表
				Method:  http.MethodGet,
				Path:    "/get_symbol_list",
				Handler: GetSymbolListHandler(serverCtx),
			},
			{
				// 管理员登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// 管理员注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				// 同步币种配置
				Method:  http.MethodPost,
				Path:    "/sync_coin_config",
				Handler: SyncCoinConfigHandler(serverCtx),
			},
			{
				// 同步错误码
				Method:  http.MethodPost,
				Path:    "/sync_error_code",
				Handler: SyncErrorCodeHandler(serverCtx),
			},
			{
				// 同步交易对配置
				Method:  http.MethodPost,
				Path:    "/sync_symbol_config",
				Handler: SyncSymbolConfigHandler(serverCtx),
			},
			{
				// 修改币种
				Method:  http.MethodPost,
				Path:    "/update_coin",
				Handler: UpdateCoinHandler(serverCtx),
			},
			{
				// 修改错误码
				Method:  http.MethodPost,
				Path:    "/update_error_code",
				Handler: UpdateErrorCodeHandler(serverCtx),
			},
			{
				// 修改交易对
				Method:  http.MethodPost,
				Path:    "/update_symbol",
				Handler: UpdateSymbolHandler(serverCtx),
			},
			{
				// 添加/更新服务的配置
				Method:  http.MethodPost,
				Path:    "/upsert_service_config",
				Handler: UpsertServiceConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin/v1"),
	)
}
