// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: match.proto

package server

import (
	"context"

	"github.com/ikun2021/gex/app/match/internal/logic"
	"github.com/ikun2021/gex/app/match/internal/svc"
	"github.com/ikun2021/gex/app/match/pb"
)

type MatchServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMatchServiceServer
}

func NewMatchServiceServer(svcCtx *svc.ServiceContext) *MatchServiceServer {
	return &MatchServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取深度
func (s *MatchServiceServer) GetDepth(ctx context.Context, in *pb.GetDepthReq) (*pb.GetDepthResp, error) {
	l := logic.NewGetDepthLogic(ctx, s.svcCtx)
	return l.GetDepth(in)
}
