Name: account.rpc
ListenOn: 0.0.0.0:20002
Timeout: 1000000
Mode: pro

Etcd:
  Hosts:
    - etcd:2379
  Key: accountRpc

JwtConf:
  SignKey: 1c5c04d04fb6705557686aff34299f9c
  ValidTime: 30d

Symbol:
  - Name: IKUN_USDT
    Id: 1
    BaseCoin: IKUN
    QuoteCoin: USDT
    QuoteCoinId: 4
    BaseCoinId: 1
    QuoteCoinPrec: 4
    BaseCoinPrec: 4
  - Name: ETH_USDT
    Id: 2
    BaseCoin: ETH
    QuoteCoin: USDT
    QuoteCoinId: 4
    BaseCoinId: 3
    QuoteCoinPrec: 4
    BaseCoinPrec: 4

Coin:
  - Name: IKUN
    Id: 1
    Precision: 4
  - Name: BTC
    Id: 2
    Precision: 4
  - Name: ETH
    Id: 3
    Precision: 4
  - Name: USDT
    Id: 4
    Precision: 4

PulsarConfig:
  hosts:
    - pulsar:6650

RedisConf:
  Host: redis:6379
  Type: node
  PingTimeout: 5s

MongoConf:
  Uri: mongodb://admin:admin@mongo:27017/?authSource=admin
  Database: trade
  OrderFinalCollection: order_final
  MatchTradeCollection: match_trade
  UserCollection: user
  ConnectTimeoutSeconds: 10

LoggerConfig:
  level: info
  stacktrace: true
  addCaller: true
  callerShip: 3
  mode: console
  json: false
  color: false
  isReport: false
