Name: gateway
Host: 0.0.0.0
Port: 8888
Timeout: 30000

AccountRpcConf:
  Etcd:
    Key: accountRpc
    Hosts:
      - etcd:2379
  NonBlock: true

MatchRpcConf:
  Etcd:
    Key: match.rpc
    Hosts:
      - etcd:2379
  NonBlock: true

QuoteRpcConf:
  Etcd:
    Key: quote.rpc
    Hosts:
      - etcd:2379
  NonBlock: true

LangPath: /app/common/errs/language

LoggerConfig:
  level: info
  stacktrace: true
  addCaller: true
  callerShip: 3
  mode: console
  json: false
  color: false
  isReport: false
