// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type GetCaptchaResp struct {
	CaptchaPic    string `json:"captcha_pic"`
	CaptchaId     string `json:"captcha_id"`
	CaptchaLength int32  `json:"captch_length"`
}

type RegisterReq struct {
	Username        string `json:"username"`              //用户名
	Password        string `json:"password"`              //密码
	ConfirmPassword string `json:"confirm_password"`      //确认密码
	PhoneNumber     int64  `json:"phone_number,optional"` //手机号
	Captcha         int64  `json:"captcha,optional"`      //验证
}

type LoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captcha_id"`
}

type LoginResp struct {
	Uid        int64  `json:"uid"`         //uid
	Username   string `json:"username"`    //用户名
	Token      string `json:"token"`       //token
	ExpireTime int64  `json:"expire_time"` //到期时间
}

type AssetInfo struct {
	Id           int64  `json:"id"`            //id
	CoinName     string `json:"coin_name"`     //币种名称
	CoinID       int32  `json:"coin_id"`       //币种id
	AvailableQty string `json:"available_qty"` //可用数量
	FrozenQty    string `json:"frozen_qty"`    //冻结数量
}

type GetUserAssetListResp struct {
	AssetList []*AssetInfo `json:"asset_list"`
}

type ValidateTokenReq struct {
	Token string `json:"token"`
}

type UserInfo struct {
	Uid      string `json:"uid"`
	Username string `json:"username"`
}

type ValidateTokenResp struct {
	UserInfo *UserInfo `json:"user_info"`
}

type AddUserAssetReq struct {
	CoinName string `json:"coin_name"`
	Qty      string `json:"qty"`
}

type CreateOrderReq struct {
	SymbolName string `json:"symbol_name" validate:"required"`       //交易对名称
	Price      string `json:"price" validate:"required,numeric"`     //价格
	Qty        string `json:"qty" validate:"required,numeric"`       //数量
	Amount     string `json:"amount"`                                //金额
	Side       int32  `json:"side" validate:"required,number"`       //方向
	OrderType  int32  `json:"order_type" validate:"required,number"` //订单类型
}

type CancelOrderReq struct {
	ID         string `json:"id"`          //订单id
	SymbolName string `json:"symbol_name"` //交易对名称
}

type GetOrderListReq struct {
	Status     []int32 `json:"status_list"` //状态
	SymbolName string  `json:"symbol_name"` //状态
	PageSize   int64   `json:"page_size"`   //分页偏远量
	Id         string  `json:"id"`
}

type OrderInfo struct {
	Id             string `json:"id"`               //id
	OrderId        string `json:"order_id"`         //订单id
	UserId         int64  `json:"user_id"`          //用户id
	SymbolName     string `json:"symbol_name"`      //交易对名
	Price          string `json:"price"`            //价格
	Qty            string `json:"qty"`              //数量
	Amount         string `json:"amount"`           //金额
	Side           int32  `json:"side"`             //方向
	Status         int32  `json:"status"`           // 状态
	OrderType      int32  `json:"order_type"`       //订单类型
	FilledQty      string `json:"filled_qty"`       //成交数量
	FilledAmount   string `json:"filled_amount"`    //成交金额
	FilledAvgPrice string `json:"filled_avg_price"` //成交均价
	CreatedAt      int64  `json:"created_at"`       //创建时间
}

type GetOrderListResp struct {
	OrderList []*OrderInfo `json:"order_list"`
	Total     int64        `json:"total"`
}
