// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: app/match/pb/match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDepthReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 档位
	Level         int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthReq) Reset() {
	*x = GetDepthReq{}
	mi := &file_app_match_pb_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthReq) ProtoMessage() {}

func (x *GetDepthReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_pb_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthReq.ProtoReflect.Descriptor instead.
func (*GetDepthReq) Descriptor() ([]byte, []int) {
	return file_app_match_pb_match_proto_rawDescGZIP(), []int{0}
}

func (x *GetDepthReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetDepthResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单簿版本
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 卖盘
	Asks []*GetDepthResp_Position `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	// 买盘
	Bids          []*GetDepthResp_Position `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthResp) Reset() {
	*x = GetDepthResp{}
	mi := &file_app_match_pb_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp) ProtoMessage() {}

func (x *GetDepthResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_pb_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp.ProtoReflect.Descriptor instead.
func (*GetDepthResp) Descriptor() ([]byte, []int) {
	return file_app_match_pb_match_proto_rawDescGZIP(), []int{1}
}

func (x *GetDepthResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetDepthResp) GetAsks() []*GetDepthResp_Position {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetDepthResp) GetBids() []*GetDepthResp_Position {
	if x != nil {
		return x.Bids
	}
	return nil
}

type GetDepthResp_Position struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数量
	BaseAmount string `protobuf:"bytes,1,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	// 价格
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// 金额
	QuoteAmount   string `protobuf:"bytes,3,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthResp_Position) Reset() {
	*x = GetDepthResp_Position{}
	mi := &file_app_match_pb_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthResp_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp_Position) ProtoMessage() {}

func (x *GetDepthResp_Position) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_pb_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp_Position.ProtoReflect.Descriptor instead.
func (*GetDepthResp_Position) Descriptor() ([]byte, []int) {
	return file_app_match_pb_match_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDepthResp_Position) GetBaseAmount() string {
	if x != nil {
		return x.BaseAmount
	}
	return ""
}

func (x *GetDepthResp_Position) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetDepthResp_Position) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

var File_app_match_pb_match_proto protoreflect.FileDescriptor

const file_app_match_pb_match_proto_rawDesc = "" +
	"\n" +
	"\x18app/match/pb/match.proto\x12\x05match\";\n" +
	"\vGetDepthReq\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\xf2\x01\n" +
	"\fGetDepthResp\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x120\n" +
	"\x04asks\x18\x02 \x03(\v2\x1c.match.GetDepthResp.PositionR\x04asks\x120\n" +
	"\x04bids\x18\x03 \x03(\v2\x1c.match.GetDepthResp.PositionR\x04bids\x1ad\n" +
	"\bPosition\x12\x1f\n" +
	"\vbase_amount\x18\x01 \x01(\tR\n" +
	"baseAmount\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12!\n" +
	"\fquote_amount\x18\x03 \x01(\tR\vquoteAmount2C\n" +
	"\fMatchService\x123\n" +
	"\bGetDepth\x12\x12.match.GetDepthReq\x1a\x13.match.GetDepthRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_match_pb_match_proto_rawDescOnce sync.Once
	file_app_match_pb_match_proto_rawDescData []byte
)

func file_app_match_pb_match_proto_rawDescGZIP() []byte {
	file_app_match_pb_match_proto_rawDescOnce.Do(func() {
		file_app_match_pb_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_match_pb_match_proto_rawDesc), len(file_app_match_pb_match_proto_rawDesc)))
	})
	return file_app_match_pb_match_proto_rawDescData
}

var file_app_match_pb_match_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_match_pb_match_proto_goTypes = []any{
	(*GetDepthReq)(nil),           // 0: match.GetDepthReq
	(*GetDepthResp)(nil),          // 1: match.GetDepthResp
	(*GetDepthResp_Position)(nil), // 2: match.GetDepthResp.Position
}
var file_app_match_pb_match_proto_depIdxs = []int32{
	2, // 0: match.GetDepthResp.asks:type_name -> match.GetDepthResp.Position
	2, // 1: match.GetDepthResp.bids:type_name -> match.GetDepthResp.Position
	0, // 2: match.MatchService.GetDepth:input_type -> match.GetDepthReq
	1, // 3: match.MatchService.GetDepth:output_type -> match.GetDepthResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_match_pb_match_proto_init() }
func file_app_match_pb_match_proto_init() {
	if File_app_match_pb_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_match_pb_match_proto_rawDesc), len(file_app_match_pb_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_match_pb_match_proto_goTypes,
		DependencyIndexes: file_app_match_pb_match_proto_depIdxs,
		MessageInfos:      file_app_match_pb_match_proto_msgTypes,
	}.Build()
	File_app_match_pb_match_proto = out.File
	file_app_match_pb_match_proto_goTypes = nil
	file_app_match_pb_match_proto_depIdxs = nil
}
