// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ikun2021/gex/app/quote/rpc/internal/dao/quote/model"
)

func newTrade(db *gorm.DB, opts ...gen.DOOption) trade {
	_trade := trade{}

	_trade.tradeDo.UseDB(db, opts...)
	_trade.tradeDo.UseModel(&model.Trade{})

	tableName := _trade.tradeDo.TableName()
	_trade.ALL = field.NewAsterisk(tableName)
	_trade.ID = field.NewInt64(tableName, "id")
	_trade.MatchID = field.NewString(tableName, "match_id")
	_trade.MatchSubID = field.NewString(tableName, "match_sub_id")
	_trade.OrderID = field.NewString(tableName, "order_id")
	_trade.UserID = field.NewInt64(tableName, "user_id")
	_trade.Symbol = field.NewString(tableName, "symbol")
	_trade.Price = field.NewString(tableName, "price")
	_trade.BaseAcmount = field.NewString(tableName, "base_acmount")
	_trade.QuoteAmount = field.NewString(tableName, "quote_amount")
	_trade.Side = field.NewInt32(tableName, "side")
	_trade.Role = field.NewInt32(tableName, "role")
	_trade.Fee = field.NewString(tableName, "fee")
	_trade.FeeCurrency = field.NewString(tableName, "fee_currency")
	_trade.CreatedAt = field.NewInt64(tableName, "created_at")

	_trade.fillFieldMap()

	return _trade
}

// trade 成交明细表_分片0
type trade struct {
	tradeDo tradeDo

	ALL         field.Asterisk
	ID          field.Int64  // 成交明细ID
	MatchID     field.String // 撮合对ID (买卖双方此ID相同，用于对账)
	MatchSubID  field.String // 本次撮合对于的Id
	OrderID     field.String // 关联的本方订单ID
	UserID      field.Int64  // 本方用户ID (分片键)
	Symbol      field.String // 交易对 (BTC/USDT)
	Price       field.String // 成交价格
	BaseAcmount field.String // 成交数量 (Base Asset)
	QuoteAmount field.String // 成交金额 (Quote Asset)
	Side        field.Int32  // 方向: 1=Buy, 2=Sell
	Role        field.Int32  // 角色: 1=Maker, 2=Taker
	Fee         field.String // 手续费数量
	FeeCurrency field.String // 手续费币种
	CreatedAt   field.Int64  // 成交时间(毫秒)

	fieldMap map[string]field.Expr
}

func (t trade) Table(newTableName string) *trade {
	t.tradeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t trade) As(alias string) *trade {
	t.tradeDo.DO = *(t.tradeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *trade) updateTableName(table string) *trade {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.MatchID = field.NewString(table, "match_id")
	t.MatchSubID = field.NewString(table, "match_sub_id")
	t.OrderID = field.NewString(table, "order_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.Symbol = field.NewString(table, "symbol")
	t.Price = field.NewString(table, "price")
	t.BaseAcmount = field.NewString(table, "base_acmount")
	t.QuoteAmount = field.NewString(table, "quote_amount")
	t.Side = field.NewInt32(table, "side")
	t.Role = field.NewInt32(table, "role")
	t.Fee = field.NewString(table, "fee")
	t.FeeCurrency = field.NewString(table, "fee_currency")
	t.CreatedAt = field.NewInt64(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *trade) WithContext(ctx context.Context) *tradeDo { return t.tradeDo.WithContext(ctx) }

func (t trade) TableName() string { return t.tradeDo.TableName() }

func (t trade) Alias() string { return t.tradeDo.Alias() }

func (t trade) Columns(cols ...field.Expr) gen.Columns { return t.tradeDo.Columns(cols...) }

func (t *trade) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *trade) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 14)
	t.fieldMap["id"] = t.ID
	t.fieldMap["match_id"] = t.MatchID
	t.fieldMap["match_sub_id"] = t.MatchSubID
	t.fieldMap["order_id"] = t.OrderID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["symbol"] = t.Symbol
	t.fieldMap["price"] = t.Price
	t.fieldMap["base_acmount"] = t.BaseAcmount
	t.fieldMap["quote_amount"] = t.QuoteAmount
	t.fieldMap["side"] = t.Side
	t.fieldMap["role"] = t.Role
	t.fieldMap["fee"] = t.Fee
	t.fieldMap["fee_currency"] = t.FeeCurrency
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t trade) clone(db *gorm.DB) trade {
	t.tradeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t trade) replaceDB(db *gorm.DB) trade {
	t.tradeDo.ReplaceDB(db)
	return t
}

type tradeDo struct{ gen.DO }

// SELECT * FROM @@table WHERE id = @id
func (t tradeDo) GetByID(id int) (result model.Trade, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM trades WHERE id = ? ")

	var executeSQL *gorm.DB
	executeSQL = t.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (t tradeDo) Debug() *tradeDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeDo) WithContext(ctx context.Context) *tradeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeDo) ReadDB() *tradeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeDo) WriteDB() *tradeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeDo) Session(config *gorm.Session) *tradeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeDo) Clauses(conds ...clause.Expression) *tradeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeDo) Returning(value interface{}, columns ...string) *tradeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeDo) Not(conds ...gen.Condition) *tradeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeDo) Or(conds ...gen.Condition) *tradeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeDo) Select(conds ...field.Expr) *tradeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeDo) Where(conds ...gen.Condition) *tradeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeDo) Order(conds ...field.Expr) *tradeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeDo) Distinct(cols ...field.Expr) *tradeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeDo) Omit(cols ...field.Expr) *tradeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeDo) Join(table schema.Tabler, on ...field.Expr) *tradeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tradeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeDo) RightJoin(table schema.Tabler, on ...field.Expr) *tradeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeDo) Group(cols ...field.Expr) *tradeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeDo) Having(conds ...gen.Condition) *tradeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeDo) Limit(limit int) *tradeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeDo) Offset(offset int) *tradeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tradeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeDo) Unscoped() *tradeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeDo) Create(values ...*model.Trade) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeDo) CreateInBatches(values []*model.Trade, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeDo) Save(values ...*model.Trade) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeDo) First() (*model.Trade, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trade), nil
	}
}

func (t tradeDo) Take() (*model.Trade, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trade), nil
	}
}

func (t tradeDo) Last() (*model.Trade, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trade), nil
	}
}

func (t tradeDo) Find() ([]*model.Trade, error) {
	result, err := t.DO.Find()
	return result.([]*model.Trade), err
}

func (t tradeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Trade, err error) {
	buf := make([]*model.Trade, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeDo) FindInBatches(result *[]*model.Trade, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeDo) Attrs(attrs ...field.AssignExpr) *tradeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeDo) Assign(attrs ...field.AssignExpr) *tradeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeDo) Joins(fields ...field.RelationField) *tradeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeDo) Preload(fields ...field.RelationField) *tradeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeDo) FirstOrInit() (*model.Trade, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trade), nil
	}
}

func (t tradeDo) FirstOrCreate() (*model.Trade, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Trade), nil
	}
}

func (t tradeDo) FindByPage(offset int, limit int) (result []*model.Trade, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeDo) Delete(models ...*model.Trade) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeDo) withDO(do gen.Dao) *tradeDo {
	t.DO = *do.(*gen.DO)
	return t
}
